### ISSUE TITLE
The last line of code is ignored if followed by triple backticks

### ISSUE THREAD

**Issue by circuitsacul** [Lunarmagpie/io#20]
```
io/run ```py
print("foo")```
```
yields "no output"

![78245](https://user-images.githubusercontent.com/55721663/226184070-a7a09b25-b049-4476-8b86-f54d4a53ee04.png)

**Comment by MicaelJarniac** [comment]
Mildly related to #19 I think.

**Comment by MicaelJarniac** [comment]
One thing worth noting is that syntax highlighting also breaks if the ending triple backticks are on a line with code. So maybe that isn't really meant to be correct code block usage.
